---
title: Rapport de stage
authors: 
- name: Fait par Golovanova Elizaveta
  affiliation: BDA, Université Grenoble Alpes 
  
lang: fr
preamble:
    - \usepackage[french]{babel}
    - \usepackage[intoc, french]{nomencl}

# to produce blinded version set to 1
blinded: 0

bibliography: bibliography.bib
# bibliography: bibliography.bib @Campbell02 @Schubert13 [@Chi81]
output: 
  rticles::asa_article:
    latex_engine: xelatex

---
\newpage
\tableofcontents 
\newpage

# Introduction

Ce rapport est consacré à l'analyse du déroulement de stage dans le cadre de la formation en Master 1, parcours Business et analyse de données, Faculté d'Economie de l'Université Grenoble Alpes. La première partie de ce rapport décrira le processus de recherche de mon stage, l'évolution de mon CV et de ma lettre de motivation, et comment ma candidature s'etait diffusée à diverses organisations. La deuxième partie du rapport parlera de l'organisation où j'ai effectué mon stage, notamment ses principales activités, le nombre d'employés. La troisième partie est réservée à la description du projet auquel j'ai participé, c'est-à-dire son objectif global et mon rôle dans sa réalisation. Dans la quatrième partie, ma mission principale sera décrite en détail. Dans la cinquième partie finale, les résultats de mon stage seront résumés.

\section{Recherche de stage}
\label{sec:first}

Dans cette section, je décrirai comment mon CV et ma lettre de motivation ont évoloué en fonction de l'expérience de recherche d'un stage. Au départ, j'ai rédigé un CV qui ne contenait que des faits nus sur ma formation, mon expérience de travail et mes compétences. Par exemple, je n'ai pas décrit mes tâches dans des emplois antérieurs, ni précisé les matières que j'ai suivies pendant mes études. Au fil du temps, je me suis rendu compte que ces détails sont importants pour se démarquer des autres candidats. J'ai réfléchi plus attentivement à mes avantages, listé mes réalisations au travail, les sujets que j'ai étudiés. J'ai également ajouté à mon CV mes qualités personnelles que les recruteurs recherchaient pour le poste d'analyste de données.

J'ai aussi initialement rédigé une lettre de motivation individuellement pour chaque poste, en précisant le nom de l'entreprise, le nom du recruteur, pour que la lettre ait l'air personnelle. Cependant, cela a pris beaucoup de temps et n'a donné aucun résultat. Comme le processus de candidature en France est administrativement compliqué, avec le temps, j'ai décidé de simplifier ma lettre de motivation et de la rendre universelle. 

Je tiens également à souligner la participation de l'université aux modifications qui ont eu lieu. Avec l'aide de Sylvian Houset, les fautes de frappe et les formulations inexactes ont été corrigées dans mon CV et ma lettre de motivation.

Après avoir modifié mon CV et ma lettre de motivation, j'ai commencé à recevoir des offres d'emploi, mais elles ne me convenaient pas pour poursuivre le processus de formation. J'ai parcouru plusieurs entretiens et noté les entreprises où je pourrais essayer d'obtenir un emploi après la fin de ma formation. En parallèle, j'ai diffusé activement mon CV aux entreprises de Grenoble et ses environs, y compris les offres envoyées par les responsables de notre master, et je me suis renseignée également sur les postes disponibles parmi les professeurs de mon université. Au total, j'ai postulé à plus de 70 endroits pour toute la recherche. Finalement, j'ai trouvé un stage dans le laboratoire GAEL avec Paolo Crosetto qui a été chargé du cours d'analyse de données en R que j'ai suivi. Ayant déjà 4 ans d'expérience dans le domaine scientifique en Russie et en cherchant la possibilité de poursuivre mon activité dans le niveau mondial, j'étais convaincue que ce stage s'intègre parfaitement dans mon projet professionnel. 

\section{Présentation de la structure de stage}
\label{sec:second}

L'organisme qui m'a accueilli est l’Institut National de Recherche pour l’Agriculture, l’alimentation et l’Environnement (INRAE). J'ai effectué un stage dans un des laboratoires affiliés à cet organisme, à savoir au laboratoire d'économie appliquée à Grenoble (GAEL). Il est composé d'une quarantaine de chercheurs auxquels s'ajoutent des post-doctorants, des doctorants et du personnel administratif et d'appui à la recherche. 


\section{Missions effectuées pendant le stage}
\label{sec:third}

L'une des principales prémisses de la plupart des modèles microéconomiques classiques est la rationalité des individus. Cependant, dans le monde réel, on peut observer que les gens, lorsqu'ils sont exposés à l'incertitude, essaient de minimiser cette incertitude autant que possible. Par exemple, un investisseur peut choisir d'investir son argent dans un compte bancaire avec un taux d'intérêt faible mais garanti, plutôt que dans des actions, qui peuvent avoir un rendement attendu élevé mais également comporter un risque de perte. Cet effet est appelé aversion au risque, il caractérise la propension des personnes à prendre telle ou telle décision face au risque. L'analyse de l'aversion au risque joue un rôle important en économie comportementale, car elle permet de mieux comprendre le fonctionnement de l'irrationalité humain. 

La thème de projet où j'ai participé pendant mon stage était "Méta-analyse de la validité externe des tâches d'élicitation des risques". Il vise à rassembler les connaissances existantes dans le domaine de l'elicitation des risques, de mieux comprendre l'état actuel de la validité externe des mesures qui aident d'identifier des risques (par méta-analyse) et donner libre accès à d'autres chercheurs et personnes intéressées en ligne et avec une base de données en constante augmentation.  

L'enjeu principal de ce projet est de repenser les tâches d'élicitation des attitudes face au risque. С'est-à-dire qu'au cours d'expériences en laboratoire, il est censé effectuer certaines tâches visant à identifier l'attitude du répondant face au risque. Une question directe peut être posée pour le déterminer, par exemple, que « Comment vous voyez-vous ? Êtes-vous généralement une personne totalement prête à prendre des risques ou essayez-vous d'éviter de prendre des risques ? » (@SOEP2007) ou il peut être la demande d'indiquer la probabilité d'être impliqué dans un événement particulier, comme tricher à un examen (@Blais2006). De même il est possible d'estimer les attitudes face au risque en utilisant une tâche d'élicitation des risques, par exemple, où le répondant est invité à choisir entre deux options plus et moins risquées (@Holt2002) ou à choisir un seul lotterie de la liste proposé (@Eckel2002). Il existe de nombreuses variantes de ces tâches, certaines impliquent une composante visuelle pour une perception plus facile (@Hunt2005, @Crosetto2013). Dans quelques tâches, les pertes sont implicites (@Menkhoff_Sakha_2017), dans d'autres seulement les gains (@Eckel2002, @Holt2002). Dans certaines tâches, il y a le choix entre deux loteries, dont l'une est plus risquée. D'autres peuvent offrir un choix de loterie à risque et un certain équivalent .
 
Il est à noter, que le projet pré-existait à mon stage, il a été lancé en 2019 sous la direction de Paolo Crosetto. Au début de mon stage, une version brute du site web avec la base de donnée assez modeste et les fonctions limité était prête, mais elle devait être entièrement repensée. En outre, lors de la creation d'un nouveau site web, j'ai pris quelques idées conceptuelles de la version originale. 

Ma mission principale était de redevelopper un site web informatif, bien structurisé, techniquement stable et jolie sur logiciel R Studio. Pour y parvenir, j'ai dû effectuer plusieurs sous-tâches. Tout d'abord, nombreux articles scientifiques différents basés sur des expériences en laboratoire ont été lus. Deuxièmement, une demande de données a été faite pour enrichir le site auprès de la communauté scientifique en suivant deux methodes : 
\begin{enumerate}
\item Paolo a envoyé le mail au ces collegues directement en utilisant la base de contact qu'il avait;
\item Les messages personnels à diffuser aux auteurs qui Paolo ne connait pas encore ont été composé. Les articles neessaires ont été selectionées par definition des requets pertinentes sur Google Scholar. Les liens sur ces articles et son information principale, tel que les noms d'auters et d'article et l'année de publication ont été collecté en utilisant le parser en Python. Ensuite, la lecture des articles par le site Scihub et extraction des mails par analyseur en Python ont été effectué. 
\end{enumerate}

Ensuit, il fallait d'alimenter le site web d'une quantité importante de base de données d'élicitation de risque qu'on a reçu dans une manière unifiée et uniformisée pour toutes les expériences. Principalement ça veut dire de faire les calculs nessecaires pour obtenir le paramètre d'aversion relative constante du risque (CRRA)[^1] pour chaque article en utilisant la methodologie speciale qui sera precisé dans la partie 5. Il était également nécessaire d'identifier sans ambiguïté d'autres variables, telles que le genre, l'age, le pays dans lequel l'expérience a été menée, la ville, etc.

[^1]: https://en.wikipedia.org/wiki/Risk_aversion

Finalement, en ulilisant cette base des données, le site web a été recréé avec l'ajout de nouvelles fonctionnalités en utilisant le package Shiny. La visualisation sur le site comprenait la conception de la structure du site, ainsi que son contenu. Par exemple, construire des distributions pour le paramètre CRRA pour chaque élément ou chaque type de question, calculer également des corrélations, creation de cartes géographiques, de tableaux avec des sources de données, etc. 

\section{Développement d’un site web consacré d'analyse de risque}
\label{sec:fourth}

\subsection{Revue de la littérature}

\subsection{Problématique économique}

La capacité à améliorer le pouvoir prédictif des tâches d'élicitation des risques est déclaré comme la mesure de la réussite du projet. 
Est-il possible d'améliorer le pouvoir prédictif des tâches liées à l'elicitation de risque ?


Plan : 
\begin{itemize}

\item  *Problématique économique* : Est-il possible d'améliorer le pouvoir prédictif des tâches liées à l'elicitation de risque ?

\item *Méthodologie* : explication du contenu ua site web


\item *Résultats* : La partie d'analyse des données que nous n'avons pas encore commencée

\item *Limitations et difficultées*

\end{itemize}

\section{Conclusion}
\label{sec:fifth}

