new_data = data.frame(desc = c('soep.md', 'soep_financial.md',
                               'soep_impulsiveness.md', 'soep_patience.md',
                               'doall.md', 'dohealth.md',
                               'dosocial.md', 'doinvest.md',
                               'dogamble.md', 'doethic.md',
                               'dorecre.md', 'BIS.md',
                               'BSSS.md', 'AuditS.md', 
                               'CDCrisk.md'), 
                                  quest = c("soep", 'soep_financial', 
                                            'soep_impulsive', 
                                            'soep_patience',
                                            'doall', 'dohealth',
                                            'dosocial', 'doinvest',
                                            'dogamble', 'doethic',
                                            'dorecre', "BIS", "BSSS",
                                            "AuditS", 'CDCrisk'
                                            ))
